# Numpy basics

In [1]:
import numpy as np

In [3]:
num = np.array([1,2,3])
alpha = np.array(['x','y','z','q'])
print(num,alpha)

[1 2 3] ['x' 'y' 'z' 'q']


In [4]:
x = np.zeros(4)
y = np.ones(5)
z = np.arange(7)

In [5]:
print(x,y,z)

[0. 0. 0. 0.] [1. 1. 1. 1. 1.] [0 1 2 3 4 5 6]


# Nd array

In [7]:
num = np.array([[1,2,3,4],[2,4,6,8]])
alpha = np.array([['a','b','c'],['b','c','d']])
print(num)
print(alpha)

[[1 2 3 4]
 [2 4 6 8]]
[['a' 'b' 'c']
 ['b' 'c' 'd']]


In [9]:
print(num.ndim)
print(alpha.ndim)

2
2


In [12]:
print(num+1)

[[2 3 4 5]
 [3 5 7 9]]


In [16]:
print(num[1][0])
print(num[0][0])

2
1


In [18]:
num1 = np.array([[1,2,3,4,5,6],[3,4,5,6,7,8]])

In [19]:
print(num.shape)
print(num1.shape)

(2, 4)
(2, 6)


In [20]:
print(num.size)
print(num1.size)

8
12


In [22]:
Num = num.reshape(4,2)
Num1 = num1.reshape(4,3)

In [23]:
print(Num)
print(Num1)

[[1 2]
 [3 4]
 [2 4]
 [6 8]]
[[1 2 3]
 [4 5 6]
 [3 4 5]
 [6 7 8]]


In [24]:
print(np.sort(num))

[[1 2 3 4]
 [2 4 6 8]]


In [25]:
print(np.sort(num1))

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]


In [26]:
x = np.where(num == 4)
y = np.where(num1 == 8)

In [27]:
print(x,y)

(array([0, 1], dtype=int64), array([3, 1], dtype=int64)) (array([1], dtype=int64), array([5], dtype=int64))


In [31]:
print(np.mean(num))
print(np.median(num))
print(np.std(num))

3.75
3.5
2.165063509461097


In [32]:
from scipy import stats

In [33]:
print(stats.mode(num))

ModeResult(mode=array([[1, 2, 3, 4]]), count=array([[1, 1, 1, 1]]))
